version: "3.8"

services:
  service1:
    build:
      context: ./service1/service_1
    image: service1
    container_name: service1
    ports:
      - "8001:8001"
    mem_limit: 256m
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8001/ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  service2:
    build:
      context: ./service2/service_2
    image: service2
    container_name: service2
    ports:
      - "8002:8002"
    mem_limit: 512m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    build:
      context: ./nginx
    image: nginx-svc
    container_name: nginx
    ports:
      - "8080:8080"
    mem_limit: 128m
    depends_on:
      service1:
        condition: service_healthy
      service2:
        condition: service_healthy

networks:
  default:
    driver: bridge
